[2023-02-24T04:56:44.580+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T04:56:44.598+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T04:56:44.663+0000] {logging_mixin.py:137} INFO - [2023-02-24T04:56:44.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T04:57:15.946+0000] {logging_mixin.py:137} INFO - [2023-02-24T04:57:15.918+0000] {timeout.py:68} ERROR - Process timed out, PID: 190
[2023-02-24T04:57:16.496+0000] {logging_mixin.py:137} INFO - [2023-02-24T04:57:16.013+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 13, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.arrays import Categorical
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 872, in get_code
  File "<frozen importlib._bootstrap_external>", line 959, in _cache_bytecode
  File "<frozen importlib._bootstrap_external>", line 973, in set_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 190
[2023-02-24T04:57:16.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T04:57:17.006+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 32.483 seconds
[2023-02-24T04:57:47.928+0000] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T04:57:47.935+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T04:57:47.949+0000] {logging_mixin.py:137} INFO - [2023-02-24T04:57:47.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T04:59:15.606+0000] {processor.py:153} INFO - Started process (PID=269) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T04:59:16.405+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T04:59:16.930+0000] {logging_mixin.py:137} INFO - [2023-02-24T04:59:16.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:00:29.735+0000] {processor.py:153} INFO - Started process (PID=316) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:00:29.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:00:29.758+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:00:29.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:01:02.812+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:02.808+0000] {timeout.py:68} ERROR - Process timed out, PID: 316
[2023-02-24T05:01:02.816+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f92f8044d40>
[2023-02-24T05:01:02.818+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2023-02-24T05:01:02.831+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2023-02-24T05:01:02.835+0000] {logging_mixin.py:137} WARNING -     def remove(k, selfref=ref(self)):
[2023-02-24T05:01:02.837+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2023-02-24T05:01:02.842+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2023-02-24T05:01:02.846+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 316
[2023-02-24T05:01:04.765+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:01:06.297+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.297+0000] {manager.py:414} ERROR - Add View Menu Error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'Scrapper', 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'fileloc_hash': 6313942600614029, 'data': '{"__version": 1, "dag": {"start_date": 1677196800.0, "dataset_triggers": [], "edge_info": {}, "fileloc": "/opt/airflow/dags/goes_scrapper_dag.py", "t ... (1417 characters truncated) ... onOperator", "_task_module": "airflow.operators.python", "_is_empty": false, "op_args": [], "op_kwargs": {}}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 2, 24, 5, 1, 4, 824318, tzinfo=Timezone('UTC')), 'dag_hash': 'a8d70db72be5513f5b9cc0241bcd500b', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-02-24T05:01:06.331+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.331+0000] {manager.py:504} INFO - Created Permission View: can delete on None
[2023-02-24T05:01:06.404+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.403+0000] {manager.py:507} ERROR - Creation of Permission View Error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ab_permission_view_permission_id_view_menu_id_uq"
DETAIL:  Key (permission_id, view_menu_id)=(1, 51) already exists.

[SQL: INSERT INTO ab_permission_view (permission_id, view_menu_id) VALUES (%(permission_id)s, %(view_menu_id)s) RETURNING ab_permission_view.id]
[parameters: {'permission_id': 1, 'view_menu_id': 51}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-02-24T05:01:06.435+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.434+0000] {manager.py:507} ERROR - Creation of Permission View Error: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ab_permission_view_permission_id_view_menu_id_uq"
DETAIL:  Key (permission_id, view_menu_id)=(2, 51) already exists.

[SQL: INSERT INTO ab_permission_view (permission_id, view_menu_id) VALUES (%(permission_id)s, %(view_menu_id)s) RETURNING ab_permission_view.id]
[parameters: {'permission_id': 2, 'view_menu_id': 51}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-02-24T05:01:06.438+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.436+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:01:06.522+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.522+0000] {dag.py:2711} INFO - Creating ORM DAG for Scrapper
[2023-02-24T05:01:06.610+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.609+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:01:06.918+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py:639 RemovedInAirflow3Warning: DAG.full_filepath is deprecated in favour of fileloc
[2023-02-24T05:01:06.931+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.920+0000] {dagbag.py:639} ERROR - Failed to write serialized DAG: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 631, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 149, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
    ret = self.one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO dag (dag_id, root_dag_id, is_paused, is_subdag, is_active, last_parsed_time, last_pickled, last_expired, scheduler_lock, pickle_id, fileloc, processor_subdir, owners, description, default_view, schedule_interval, timetable_description, max_active_tasks, max_active_runs, has_task_concurrency_limits, has_import_errors, next_dagrun, next_dagrun_data_interval_start, next_dagrun_data_interval_end, next_dagrun_create_after) VALUES (%(dag_id)s, %(root_dag_id)s, %(is_paused)s, %(is_subdag)s, %(is_active)s, %(last_parsed_time)s, %(last_pickled)s, %(last_expired)s, %(scheduler_lock)s, %(pickle_id)s, %(fileloc)s, %(processor_subdir)s, %(owners)s, %(description)s, %(default_view)s, %(schedule_interval)s, %(timetable_description)s, %(max_active_tasks)s, %(max_active_runs)s, %(has_task_concurrency_limits)s, %(has_import_errors)s, %(next_dagrun)s, %(next_dagrun_data_interval_start)s, %(next_dagrun_data_interval_end)s, %(next_dagrun_create_after)s)]
[parameters: {'dag_id': 'Scrapper', 'root_dag_id': None, 'is_paused': True, 'is_subdag': False, 'is_active': True, 'last_parsed_time': datetime.datetime(2023, 2, 24, 5, 1, 6, 587466, tzinfo=Timezone('UTC')), 'last_pickled': None, 'last_expired': None, 'scheduler_lock': None, 'pickle_id': None, 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'processor_subdir': '/opt/airflow/dags', 'owners': 'airflow', 'description': None, 'default_view': 'grid', 'schedule_interval': '"0 0 * * *"', 'timetable_description': 'At 00:00', 'max_active_tasks': 16, 'max_active_runs': 16, 'has_task_concurrency_limits': False, 'has_import_errors': False, 'next_dagrun': DateTime(2023, 2, 24, 0, 0, 0, tzinfo=Timezone('UTC')), 'next_dagrun_data_interval_start': DateTime(2023, 2, 24, 0, 0, 0, tzinfo=Timezone('UTC')), 'next_dagrun_data_interval_end': DateTime(2023, 2, 25, 0, 0, 0, tzinfo=Timezone('UTC')), 'next_dagrun_create_after': DateTime(2023, 2, 25, 0, 0, 0, tzinfo=Timezone('UTC'))}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-02-24T05:01:06.932+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:06.932+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:01:06.935+0000] {processor.py:178} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 174, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 158, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 768, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 645, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 660, in sync_to_db
    self.dags.values(), processor_subdir=processor_subdir, session=session
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2701, in bulk_write_to_db
    orm_dags: list[DagModel] = with_row_locks(query, of=DagModel, session=session).all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO dag (dag_id, root_dag_id, is_paused, is_subdag, is_active, last_parsed_time, last_pickled, last_expired, scheduler_lock, pickle_id, fileloc, processor_subdir, owners, description, default_view, schedule_interval, timetable_description, max_active_tasks, max_active_runs, has_task_concurrency_limits, has_import_errors, next_dagrun, next_dagrun_data_interval_start, next_dagrun_data_interval_end, next_dagrun_create_after) VALUES (%(dag_id)s, %(root_dag_id)s, %(is_paused)s, %(is_subdag)s, %(is_active)s, %(last_parsed_time)s, %(last_pickled)s, %(last_expired)s, %(scheduler_lock)s, %(pickle_id)s, %(fileloc)s, %(processor_subdir)s, %(owners)s, %(description)s, %(default_view)s, %(schedule_interval)s, %(timetable_description)s, %(max_active_tasks)s, %(max_active_runs)s, %(has_task_concurrency_limits)s, %(has_import_errors)s, %(next_dagrun)s, %(next_dagrun_data_interval_start)s, %(next_dagrun_data_interval_end)s, %(next_dagrun_create_after)s)]
[parameters: {'dag_id': 'Scrapper', 'root_dag_id': None, 'is_paused': True, 'is_subdag': False, 'is_active': True, 'last_parsed_time': datetime.datetime(2023, 2, 24, 5, 1, 6, 587466, tzinfo=Timezone('UTC')), 'last_pickled': None, 'last_expired': None, 'scheduler_lock': None, 'pickle_id': None, 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'processor_subdir': '/opt/airflow/dags', 'owners': 'airflow', 'description': None, 'default_view': 'grid', 'schedule_interval': '"0 0 * * *"', 'timetable_description': 'At 00:00', 'max_active_tasks': 16, 'max_active_runs': 16, 'has_task_concurrency_limits': False, 'has_import_errors': False, 'next_dagrun': DateTime(2023, 2, 24, 0, 0, 0, tzinfo=Timezone('UTC')), 'next_dagrun_data_interval_start': DateTime(2023, 2, 24, 0, 0, 0, tzinfo=Timezone('UTC')), 'next_dagrun_data_interval_end': DateTime(2023, 2, 25, 0, 0, 0, tzinfo=Timezone('UTC')), 'next_dagrun_create_after': DateTime(2023, 2, 25, 0, 0, 0, tzinfo=Timezone('UTC'))}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-02-24T05:01:37.680+0000] {processor.py:153} INFO - Started process (PID=374) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:01:37.687+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:01:37.697+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:37.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:01:43.516+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:01:43.857+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:43.855+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:01:44.042+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:01:44.041+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:01:44.158+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.506 seconds
[2023-02-24T05:02:14.883+0000] {processor.py:153} INFO - Started process (PID=403) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:02:14.898+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:02:14.902+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:02:14.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:02:23.255+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:02:24.338+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:02:24.329+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:02:24.680+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:02:24.678+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:02:24.913+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 10.050 seconds
[2023-02-24T05:02:55.253+0000] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:02:55.257+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:02:55.260+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:02:55.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:03:00.028+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:03:00.297+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:03:00.295+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:03:00.403+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:03:00.403+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:03:00.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.236 seconds
[2023-02-24T05:03:30.870+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:03:30.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:03:30.879+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:03:30.879+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:03:35.504+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:03:35.763+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:03:35.761+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:03:35.912+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:03:35.912+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:03:36.051+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.196 seconds
[2023-02-24T05:04:06.868+0000] {processor.py:153} INFO - Started process (PID=504) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:04:06.871+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:04:06.874+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:04:06.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:04:10.736+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:04:11.213+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:04:11.211+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:04:11.374+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:04:11.374+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:04:11.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.639 seconds
[2023-02-24T05:04:41.863+0000] {processor.py:153} INFO - Started process (PID=542) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:04:41.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:04:41.868+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:04:41.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:04:44.930+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:04:44.997+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:04:44.996+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:04:45.073+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:04:45.072+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:04:45.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 3.259 seconds
[2023-02-24T05:05:15.531+0000] {processor.py:153} INFO - Started process (PID=573) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:05:15.538+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:05:15.550+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:05:15.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:05:52.089+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:05:46.234+0000] {timeout.py:68} ERROR - Process timed out, PID: 573
[2023-02-24T05:09:26.413+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:05:54.769+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 126, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 229, in _load_service_model
    service_name, 'service-2', api_version=api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 406, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 306, in list_available_services
    for d in os.listdir(possible_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 307, in <listcomp>
    if os.path.isdir(os.path.join(possible_path, d))
  File "/usr/local/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 573
[2023-02-24T05:13:34.795+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:15:44.426+0000] {processor.py:178} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 174, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 158, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 756, in process_file
    self.update_import_errors(session, dagbag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 544, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-02-24T05:16:23.819+0000] {processor.py:153} INFO - Started process (PID=609) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:16:23.827+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:16:23.839+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:16:23.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:16:54.651+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:16:54.369+0000] {timeout.py:68} ERROR - Process timed out, PID: 609
[2023-02-24T05:17:02.530+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:16:55.062+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 141, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 197, in _create_client_class
    base_classes=bases,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/utils.py", line 65, in _handler
    module = import_module(module)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/utils.py", line 56, in import_module
    __import__(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 16, in <module>
    from boto3.s3.transfer import (
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 132, in <module>
    from s3transfer.manager import TransferConfig as S3TransferConfig
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/manager.py", line 32, in <module>
    from s3transfer.upload import UploadSubmissionTask
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 32, in <module>
    class AggregatedProgressCallback:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 609
[2023-02-24T05:17:02.972+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:17:21.183+0000] {processor.py:178} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 174, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 158, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 756, in process_file
    self.update_import_errors(session, dagbag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 544, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3365, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2199, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-02-24T05:18:57.822+0000] {processor.py:153} INFO - Started process (PID=643) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:18:57.846+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:18:57.850+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:18:57.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:19:32.852+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:19:28.036+0000] {timeout.py:68} ERROR - Process timed out, PID: 643
[2023-02-24T05:34:16.352+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:19:44.925+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 129, in create_client
    service_name, api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 236, in _load_service_endpoints_ruleset
    service_name, 'endpoint-rule-set-1', api_version=api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 406, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 314, in list_available_services
    full_dirname, api_version, type_name
  File "/usr/local/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 643
[2023-02-24T05:34:18.281+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:34:24.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 927.079 seconds
[2023-02-24T05:34:56.530+0000] {processor.py:153} INFO - Started process (PID=688) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:34:56.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:34:56.570+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:34:56.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:35:08.008+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:35:08.218+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:08.218+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:35:08.346+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:08.345+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:35:08.556+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py:639 RemovedInAirflow3Warning: DAG.full_filepath is deprecated in favour of fileloc
[2023-02-24T05:35:08.587+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:08.558+0000] {dagbag.py:639} ERROR - Failed to write serialized DAG: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 631, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 149, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
    ret = self.one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'Scrapper', 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'fileloc_hash': 6313942600614029, 'data': '{"__version": 1, "dag": {"start_date": 1677196800.0, "dataset_triggers": [], "edge_info": {}, "fileloc": "/opt/airflow/dags/goes_scrapper_dag.py", "t ... (1417 characters truncated) ... onOperator", "_task_module": "airflow.operators.python", "_is_empty": false, "op_args": [], "op_kwargs": {}}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 2, 24, 5, 35, 8, 39109, tzinfo=Timezone('UTC')), 'dag_hash': 'a8d70db72be5513f5b9cc0241bcd500b', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-02-24T05:35:08.589+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:08.588+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:35:08.591+0000] {processor.py:178} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 174, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 158, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 768, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 645, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 660, in sync_to_db
    self.dags.values(), processor_subdir=processor_subdir, session=session
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2701, in bulk_write_to_db
    orm_dags: list[DagModel] = with_row_locks(query, of=DagModel, session=session).all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'Scrapper', 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'fileloc_hash': 6313942600614029, 'data': '{"__version": 1, "dag": {"start_date": 1677196800.0, "dataset_triggers": [], "edge_info": {}, "fileloc": "/opt/airflow/dags/goes_scrapper_dag.py", "t ... (1417 characters truncated) ... onOperator", "_task_module": "airflow.operators.python", "_is_empty": false, "op_args": [], "op_kwargs": {}}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 2, 24, 5, 35, 8, 39109, tzinfo=Timezone('UTC')), 'dag_hash': 'a8d70db72be5513f5b9cc0241bcd500b', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-02-24T05:35:39.235+0000] {processor.py:153} INFO - Started process (PID=725) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:35:39.249+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:35:39.259+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:39.258+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:35:45.167+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:35:45.378+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:45.377+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:35:45.463+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:35:45.462+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:35:45.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.346 seconds
[2023-02-24T05:36:15.989+0000] {processor.py:153} INFO - Started process (PID=761) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:36:15.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:36:15.999+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:36:15.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:36:20.388+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:36:21.239+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:36:21.233+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:36:22.245+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:36:22.224+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:36:23.191+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 7.221 seconds
[2023-02-24T05:36:53.978+0000] {processor.py:153} INFO - Started process (PID=797) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:36:53.981+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:36:53.983+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:36:53.983+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:37:04.556+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:46:11.335+0000] {processor.py:153} INFO - Started process (PID=829) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:46:11.347+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:46:11.365+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:46:11.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:46:25.591+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:46:26.072+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:46:26.071+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:46:26.431+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:46:26.431+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T05:46:26.865+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py:639 RemovedInAirflow3Warning: DAG.full_filepath is deprecated in favour of fileloc
[2023-02-24T05:46:26.891+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:46:26.867+0000] {dagbag.py:639} ERROR - Failed to write serialized DAG: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 631, in _serialize_dag_capturing_errors
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/serialized_dag.py", line 149, in write_dag
    (timezone.utcnow() - timedelta(seconds=min_update_interval)) < cls.last_updated,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2893, in scalar
    ret = self.one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'Scrapper', 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'fileloc_hash': 6313942600614029, 'data': '{"__version": 1, "dag": {"start_date": 1677196800.0, "dataset_triggers": [], "edge_info": {}, "fileloc": "/opt/airflow/dags/goes_scrapper_dag.py", "t ... (1417 characters truncated) ... onOperator", "_task_module": "airflow.operators.python", "_is_empty": false, "op_args": [], "op_kwargs": {}}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 2, 24, 5, 46, 25, 696353, tzinfo=Timezone('UTC')), 'dag_hash': 'a8d70db72be5513f5b9cc0241bcd500b', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-02-24T05:46:26.894+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:46:26.894+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T05:46:26.897+0000] {processor.py:178} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 174, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 158, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 768, in process_file
    dagbag.sync_to_db(processor_subdir=self._dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 645, in sync_to_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 384, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 660, in sync_to_db
    self.dags.values(), processor_subdir=processor_subdir, session=session
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dag.py", line 2701, in bulk_write_to_db
    orm_dags: list[DagModel] = with_row_locks(query, of=DagModel, session=session).all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1553, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 608, in _assert_active
    code="7s2a",
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(Scrapper) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'Scrapper', 'fileloc': '/opt/airflow/dags/goes_scrapper_dag.py', 'fileloc_hash': 6313942600614029, 'data': '{"__version": 1, "dag": {"start_date": 1677196800.0, "dataset_triggers": [], "edge_info": {}, "fileloc": "/opt/airflow/dags/goes_scrapper_dag.py", "t ... (1417 characters truncated) ... onOperator", "_task_module": "airflow.operators.python", "_is_empty": false, "op_args": [], "op_kwargs": {}}], "dag_dependencies": [], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 2, 24, 5, 46, 25, 696353, tzinfo=Timezone('UTC')), 'dag_hash': 'a8d70db72be5513f5b9cc0241bcd500b', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-02-24T05:46:57.262+0000] {processor.py:153} INFO - Started process (PID=872) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:46:57.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T05:46:57.293+0000] {logging_mixin.py:137} INFO - [2023-02-24T05:46:57.282+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T05:47:20.445+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:05:34.089+0000] {processor.py:153} INFO - Started process (PID=883) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:05:34.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:05:34.256+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:05:34.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:07:35.291+0000] {processor.py:153} INFO - Started process (PID=923) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:07:35.390+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:07:35.564+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:07:35.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:07:59.155+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:08:00.719+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:00.718+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:Scrapper_goes18
[2023-02-24T06:08:00.783+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:00.783+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:Scrapper_goes18
[2023-02-24T06:08:00.829+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:00.828+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:Scrapper_goes18
[2023-02-24T06:08:00.833+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:00.831+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:08:00.934+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:00.932+0000] {dag.py:2711} INFO - Creating ORM DAG for Scrapper_goes18
[2023-02-24T06:08:01.029+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:01.028+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:08:01.188+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 26.099 seconds
[2023-02-24T06:08:31.421+0000] {processor.py:153} INFO - Started process (PID=976) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:08:31.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:08:31.430+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:31.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:08:34.420+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:08:34.491+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:34.490+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:08:34.614+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:08:34.613+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:08:34.711+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 3.127 seconds
[2023-02-24T06:09:05.211+0000] {processor.py:153} INFO - Started process (PID=1012) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:09:05.216+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:09:05.220+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:09:05.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:09:09.993+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:09:10.082+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:09:10.077+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:09:10.203+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:09:10.202+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:09:10.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.136 seconds
[2023-02-24T06:09:40.704+0000] {processor.py:153} INFO - Started process (PID=1042) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:09:40.717+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:09:40.773+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:09:40.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:09:56.810+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:09:57.083+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:09:57.080+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:09:57.542+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:09:57.531+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:09:57.806+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 17.184 seconds
[2023-02-24T06:10:28.084+0000] {processor.py:153} INFO - Started process (PID=1088) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:10:28.100+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:10:28.114+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:10:28.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:10:34.751+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:10:34.945+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:10:34.940+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:10:35.158+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:10:35.158+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:10:35.260+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 7.228 seconds
[2023-02-24T06:11:06.276+0000] {processor.py:153} INFO - Started process (PID=1124) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:11:06.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:11:06.311+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:11:06.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:11:10.289+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:11:10.378+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:11:10.376+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:11:10.504+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:11:10.504+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:11:10.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.377 seconds
[2023-02-24T06:11:41.122+0000] {processor.py:153} INFO - Started process (PID=1153) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:11:41.126+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:11:41.130+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:11:41.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:11:45.047+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:11:45.132+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:11:45.129+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:11:45.249+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:11:45.248+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:11:45.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.234 seconds
[2023-02-24T06:12:16.056+0000] {processor.py:153} INFO - Started process (PID=1187) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:12:16.067+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:12:16.071+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:12:16.071+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:12:22.476+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:12:22.569+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:12:22.566+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:12:22.699+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:12:22.698+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:12:22.797+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.761 seconds
[2023-02-24T06:12:52.999+0000] {processor.py:153} INFO - Started process (PID=1216) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:12:53.003+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:12:53.007+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:12:53.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:12:55.479+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:12:55.571+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:12:55.569+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:12:55.871+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:12:55.871+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:12:56.029+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 3.051 seconds
[2023-02-24T06:13:26.602+0000] {processor.py:153} INFO - Started process (PID=1253) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:13:26.608+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:13:26.612+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:13:26.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:13:31.326+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:13:31.493+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:13:31.492+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:13:31.657+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:13:31.648+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:13:31.763+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.177 seconds
[2023-02-24T06:14:02.430+0000] {processor.py:153} INFO - Started process (PID=1282) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:14:02.473+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:14:02.476+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:14:02.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:14:08.047+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:14:08.369+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:14:08.363+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:14:08.671+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:14:08.669+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:14:08.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.463 seconds
[2023-02-24T06:14:39.847+0000] {processor.py:153} INFO - Started process (PID=1309) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:14:39.849+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:14:39.851+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:14:39.851+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:14:44.132+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:14:44.268+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:14:44.264+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:14:44.372+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:14:44.372+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:14:44.455+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.614 seconds
[2023-02-24T06:15:14.749+0000] {processor.py:153} INFO - Started process (PID=1345) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:15:14.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:15:14.756+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:15:14.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:15:25.471+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:15:26.071+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:15:26.069+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:15:26.386+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:15:26.383+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:15:26.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 11.851 seconds
[2023-02-24T06:15:56.888+0000] {processor.py:153} INFO - Started process (PID=1380) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:15:56.892+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:15:56.904+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:15:56.903+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:16:02.392+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:16:02.696+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:16:02.695+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:16:02.856+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:16:02.855+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:16:02.958+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.091 seconds
[2023-02-24T06:16:34.201+0000] {processor.py:153} INFO - Started process (PID=1417) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:16:34.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:16:34.217+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:16:34.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:17:23.761+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:17:23.747+0000] {timeout.py:68} ERROR - Process timed out, PID: 1417
[2023-02-24T06:17:23.763+0000] {logging_mixin.py:137} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f92f8044d40>
[2023-02-24T06:17:23.764+0000] {logging_mixin.py:137} WARNING - Traceback (most recent call last):
[2023-02-24T06:17:23.765+0000] {logging_mixin.py:137} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 358, in remove
[2023-02-24T06:17:23.767+0000] {logging_mixin.py:137} WARNING -     def remove(k, selfref=ref(self)):
[2023-02-24T06:17:23.769+0000] {logging_mixin.py:137} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2023-02-24T06:17:23.774+0000] {logging_mixin.py:137} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2023-02-24T06:17:23.775+0000] {logging_mixin.py:137} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 1417
[2023-02-24T06:20:24.441+0000] {processor.py:153} INFO - Started process (PID=1438) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:20:24.457+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:20:24.475+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:20:24.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:21:13.895+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:21:13.840+0000] {timeout.py:68} ERROR - Process timed out, PID: 1438
[2023-02-24T06:21:14.171+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:21:13.942+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 13, in <module>
    import pandas as pd
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
  File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/tslibs/__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas/_libs/tslibs/conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "<frozen importlib._bootstrap>", line 416, in parent
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 1438
[2023-02-24T06:21:14.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:21:14.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 50.368 seconds
[2023-02-24T06:21:45.799+0000] {processor.py:153} INFO - Started process (PID=1465) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:21:45.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:21:45.821+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:21:45.812+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:21:54.402+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:21:54.835+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:21:54.833+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:21:54.979+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:21:54.978+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:21:55.124+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 9.357 seconds
[2023-02-24T06:22:26.003+0000] {processor.py:153} INFO - Started process (PID=1502) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:22:26.020+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:22:26.041+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:22:26.041+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:22:35.357+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:22:35.685+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:22:35.683+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:22:35.889+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:22:35.889+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:22:36.013+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 10.047 seconds
[2023-02-24T06:23:07.450+0000] {processor.py:153} INFO - Started process (PID=1538) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:23:07.461+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:23:07.468+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:23:07.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:23:19.363+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:23:20.143+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:23:20.141+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:23:20.507+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:23:20.499+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:23:20.818+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 13.391 seconds
[2023-02-24T06:23:51.430+0000] {processor.py:153} INFO - Started process (PID=1574) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:23:51.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:23:51.440+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:23:51.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:24:01.435+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:24:01.606+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:24:01.604+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:24:01.713+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:24:01.712+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:24:01.788+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 10.378 seconds
[2023-02-24T06:24:32.971+0000] {processor.py:153} INFO - Started process (PID=1610) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:24:32.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:24:32.978+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:24:32.977+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:24:45.308+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:24:45.978+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:24:45.975+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:24:46.196+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:24:46.196+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:24:46.429+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 13.478 seconds
[2023-02-24T06:25:17.132+0000] {processor.py:153} INFO - Started process (PID=1640) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:25:17.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:25:17.166+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:25:17.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:25:50.781+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:25:47.729+0000] {timeout.py:68} ERROR - Process timed out, PID: 1640
[2023-02-24T06:29:34.733+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:25:55.279+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/.aws/models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 126, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 229, in _load_service_model
    service_name, 'service-2', api_version=api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 406, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 298, in list_available_services
    for possible_path in self._potential_locations():
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 478, in _potential_locations
    if os.path.isdir(path):
  File "/usr/local/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 1640
[2023-02-24T06:29:34.982+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:30:40.385+0000] {processor.py:153} INFO - Started process (PID=1668) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:30:40.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:30:40.445+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:30:40.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:31:01.353+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:31:01.823+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:31:01.821+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:31:02.022+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:31:02.021+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:31:02.137+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 22.005 seconds
[2023-02-24T06:31:32.752+0000] {processor.py:153} INFO - Started process (PID=1712) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:31:32.758+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:31:32.773+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:31:32.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:31:38.544+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:31:38.808+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:31:38.805+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:31:39.414+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:31:39.404+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:31:39.696+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.983 seconds
[2023-02-24T06:32:10.611+0000] {processor.py:153} INFO - Started process (PID=1746) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:32:10.623+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:32:10.631+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:32:10.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:32:15.773+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:32:15.922+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:32:15.920+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:32:16.197+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:32:16.197+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:32:16.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.743 seconds
[2023-02-24T06:32:47.036+0000] {processor.py:153} INFO - Started process (PID=1775) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:32:47.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:32:47.047+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:32:47.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:32:50.241+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:32:50.338+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:32:50.336+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:32:50.473+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:32:50.472+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:32:50.598+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 3.587 seconds
[2023-02-24T06:33:21.453+0000] {processor.py:153} INFO - Started process (PID=1811) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:33:21.462+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:33:21.468+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:33:21.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:33:25.190+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:33:25.266+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:33:25.265+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:33:25.337+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:33:25.336+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:33:25.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 3.978 seconds
[2023-02-24T06:33:56.219+0000] {processor.py:153} INFO - Started process (PID=1847) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:33:56.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:33:56.230+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:33:56.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:41:09.857+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:34:27.952+0000] {timeout.py:68} ERROR - Process timed out, PID: 1847
[2023-02-24T06:41:20.425+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:41:10.333+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 956, in create_client
    defaults_mode = self._resolve_defaults_mode(config, config_store)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 1022, in _resolve_defaults_mode
    'default_config_resolver'
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 812, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 1108, in get_component
    self._components[name] = factory()
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 210, in create_default_config_resolver
    defaults = loader.load_data('sdk-default-configuration')
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 471, in load_data
    data, _ = self.load_data_with_path(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 448, in load_data_with_path
    found = self.file_loader.load_file(possible_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 194, in load_file
    data = self._load_file(file_path + ext, open_method)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 181, in _load_file
    return json.loads(payload, object_pairs_hook=OrderedDict)
  File "/usr/local/lib/python3.7/json/__init__.py", line 336, in loads
    if s.startswith('\ufeff'):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 1847
[2023-02-24T06:41:21.041+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:41:40.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 464.106 seconds
[2023-02-24T06:44:31.972+0000] {processor.py:153} INFO - Started process (PID=133) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:44:32.004+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:44:32.020+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:44:32.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:44:45.903+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:44:47.260+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:44:47.249+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:44:47.808+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:44:47.808+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:44:48.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 16.119 seconds
[2023-02-24T06:45:19.504+0000] {processor.py:153} INFO - Started process (PID=176) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:45:19.513+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:45:19.526+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:45:19.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:45:30.474+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:45:30.662+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:45:30.649+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:45:30.942+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:45:30.941+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:45:31.143+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 11.769 seconds
[2023-02-24T06:46:01.681+0000] {processor.py:153} INFO - Started process (PID=212) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:46:01.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:46:01.786+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:46:01.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:46:06.197+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:46:06.372+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:46:06.369+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:46:06.590+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:46:06.589+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:46:06.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.088 seconds
[2023-02-24T06:46:37.364+0000] {processor.py:153} INFO - Started process (PID=248) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:46:37.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:46:37.372+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:46:37.371+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:46:42.344+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:46:42.544+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:46:42.542+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:46:42.687+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:46:42.686+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:46:42.802+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.452 seconds
[2023-02-24T06:47:13.472+0000] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:47:13.475+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:47:13.480+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:47:13.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:47:19.001+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:47:19.204+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:47:19.202+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:47:19.418+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:47:19.418+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:47:19.534+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.079 seconds
[2023-02-24T06:47:50.233+0000] {processor.py:153} INFO - Started process (PID=305) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:47:50.236+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:47:50.239+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:47:50.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:47:55.457+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:47:55.748+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:47:55.745+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:47:55.941+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:47:55.941+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:47:56.097+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.877 seconds
[2023-02-24T06:48:26.819+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:48:26.822+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:48:26.825+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:48:26.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:48:30.371+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:48:30.482+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:48:30.480+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:48:30.615+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:48:30.614+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:48:30.714+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 3.907 seconds
[2023-02-24T06:49:01.805+0000] {processor.py:153} INFO - Started process (PID=377) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:49:01.812+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:49:01.816+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:49:01.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:49:07.652+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:49:07.828+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:49:07.826+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:49:07.974+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:49:07.973+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:49:08.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.305 seconds
[2023-02-24T06:49:39.004+0000] {processor.py:153} INFO - Started process (PID=413) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:49:39.017+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:49:39.023+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:49:39.021+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:49:45.459+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:49:45.827+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:49:45.826+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:49:46.046+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:49:46.045+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:49:46.354+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 7.380 seconds
[2023-02-24T06:50:16.916+0000] {processor.py:153} INFO - Started process (PID=442) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:50:16.922+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:50:16.929+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:50:16.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:50:27.531+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:50:27.793+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:50:27.791+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:50:27.923+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:50:27.922+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:50:28.076+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 11.174 seconds
[2023-02-24T06:50:58.548+0000] {processor.py:153} INFO - Started process (PID=478) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:50:58.555+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:50:58.561+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:50:58.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:51:29.314+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:51:28.933+0000] {timeout.py:68} ERROR - Process timed out, PID: 478
[2023-02-24T06:51:31.165+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:51:29.411+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 129, in create_client
    service_name, api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 236, in _load_service_endpoints_ruleset
    service_name, 'endpoint-rule-set-1', api_version=api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 406, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 311, in list_available_services
    api_versions = os.listdir(full_dirname)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 478
[2023-02-24T06:51:31.186+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:51:32.639+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 34.006 seconds
[2023-02-24T06:52:03.941+0000] {processor.py:153} INFO - Started process (PID=515) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:52:03.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:52:03.952+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:52:03.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:52:08.195+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:52:09.186+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:52:09.166+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:52:09.472+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:52:09.471+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:52:09.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.750 seconds
[2023-02-24T06:52:40.429+0000] {processor.py:153} INFO - Started process (PID=551) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:52:40.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:52:40.442+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:52:40.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:52:46.069+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:52:46.400+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:52:46.399+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:52:46.598+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:52:46.597+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:52:46.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 6.348 seconds
[2023-02-24T06:53:17.623+0000] {processor.py:153} INFO - Started process (PID=578) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:53:17.626+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:53:17.631+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:53:17.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:53:21.482+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:53:21.780+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:53:21.767+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:53:22.051+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:53:22.050+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:53:22.170+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.558 seconds
[2023-02-24T06:53:52.441+0000] {processor.py:153} INFO - Started process (PID=607) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:53:52.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:53:52.449+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:53:52.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:53:56.291+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:53:56.399+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:53:56.397+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:53:56.564+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:53:56.564+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:53:56.648+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.217 seconds
[2023-02-24T06:54:27.321+0000] {processor.py:153} INFO - Started process (PID=643) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:54:27.325+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:54:27.329+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:54:27.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:54:31.318+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:54:31.461+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:54:31.459+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:54:31.609+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:54:31.609+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:54:31.691+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 4.386 seconds
[2023-02-24T06:55:02.824+0000] {processor.py:153} INFO - Started process (PID=679) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:55:02.831+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:55:02.852+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:55:02.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:55:09.417+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:55:10.457+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:55:10.427+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:55:10.814+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:55:10.814+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:55:11.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 8.303 seconds
[2023-02-24T06:55:42.006+0000] {processor.py:153} INFO - Started process (PID=715) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:55:42.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:55:42.025+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:55:42.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:55:52.828+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:55:53.168+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:55:53.166+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:55:53.341+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:55:53.340+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:55:53.448+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 11.473 seconds
[2023-02-24T06:56:24.214+0000] {processor.py:153} INFO - Started process (PID=751) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:56:24.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:56:24.230+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:56:24.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:56:32.838+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:56:33.093+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:56:33.091+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:56:33.322+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:56:33.321+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:56:33.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 9.326 seconds
[2023-02-24T06:57:04.851+0000] {processor.py:153} INFO - Started process (PID=788) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:57:04.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:57:04.887+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:57:04.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:57:18.777+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:57:52.231+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:57:52.181+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:58:51.747+0000] {processor.py:153} INFO - Started process (PID=809) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:58:51.750+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:58:51.755+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:58:51.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:58:56.740+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:58:57.160+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:58:57.159+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:58:57.315+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:58:57.315+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:58:57.419+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 5.910 seconds
[2023-02-24T06:59:27.916+0000] {processor.py:153} INFO - Started process (PID=845) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:59:27.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T06:59:27.920+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:59:27.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:59:30.296+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Scrapper_goes18']) retrieved from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T06:59:30.360+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:59:30.359+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-24T06:59:30.419+0000] {logging_mixin.py:137} INFO - [2023-02-24T06:59:30.419+0000] {dag.py:3441} INFO - Setting next_dagrun for Scrapper_goes18 to 2023-02-24T00:00:00+00:00, run_after=2023-02-25T00:00:00+00:00
[2023-02-24T06:59:30.463+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/goes_scrapper_dag.py took 2.555 seconds
[2023-02-24T07:00:00.901+0000] {processor.py:153} INFO - Started process (PID=881) to work on /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T07:00:00.907+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/goes_scrapper_dag.py for tasks to queue
[2023-02-24T07:00:00.911+0000] {logging_mixin.py:137} INFO - [2023-02-24T07:00:00.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/goes_scrapper_dag.py
[2023-02-24T07:07:38.556+0000] {logging_mixin.py:137} INFO - [2023-02-24T07:00:50.692+0000] {timeout.py:68} ERROR - Process timed out, PID: 881
[2023-02-24T07:07:41.056+0000] {logging_mixin.py:137} INFO - [2023-02-24T07:07:38.638+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/goes_scrapper_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/goes_scrapper_dag.py", line 25, in <module>
    aws_secret_access_key = os.environ.get('AWS_SECRET_KEY')
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/session.py", line 309, in client
    config=config,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/session.py", line 986, in create_client
    auth_token=auth_token,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 126, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 229, in _load_service_model
    service_name, 'service-2', api_version=api_version
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 406, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 306, in list_available_services
    for d in os.listdir(possible_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/loaders.py", line 307, in <listcomp>
    if os.path.isdir(os.path.join(possible_path, d))
  File "/usr/local/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/goes_scrapper_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.5.1/best-practices.html#reducing-dag-complexity, PID: 881
[2023-02-24T07:07:41.901+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/goes_scrapper_dag.py
